export function approvalRefs() {
  return {
    noRef: 0,
    employeeNameRefVal: 1,
    addProductBtnRef: 3,
    ewayBillNoRef: 4,
    cancelBtnRef: 5,
    paymentTypeRef: 6,
    paymentModeRef: 7,
    prefixesRef: 8,
    subPrefixesRef: 9,
    invoiceDateRef: 10,
    placeOfSupplyRef: 11,
    packingChargeRef: 12,
    shippingChargeRef: 13,
    discountRef: 14,
    receivedPaymentRef: 15,
    saveBtnRef: 16,
    saveNewRef: 17,
    printNewRef: 18,
    printRef: 19,
    linkpaymentRef: 20,
    productNameRef: 21,
    barcodeRef: 22,
    mrpRef: 23,
    qtyRef: 24,
    productDiscountPercentRef: 25,
    productDiscountAmountRef: 26,
    cgstRef: 27,
    cgstAmountRef: 28,
    sgstRef: 29,
    sgstAmountRef: 30,
    igstRef: 31,
    igstAmountRef: 32,
    cessRef: 33,
    amountRef: 34,
    deleteBtnRef: 35,
    addRowRef: 36,
    grossWeightGmsRef: 37,
    wastagePercentRef: 38,
    wastageGmsRef: 39,
    netWeightRef: 40,
    purity: 41,

    firstIndexProductNameRef: 210,
    employeeListFirstIndexRef: 1000
  };
}
