export function kotRefs() {
    return {
        noRef                         : 0,
        customerNameRefVal            : 1,
        addCustomerBtnRef             : 2,
        addProductBtnRef              : 3,
        prefixesRef                   : 4,
        subPrefixesRef                : 5,
        invoiceDateRef                : 6,
        cancelBtnRef                  : 7,
        orderTypeRef                  : 8,
        waiterNameRef                 : 9,
        chairNoRef                    : 10,
        paxRef                        : 11,
        packingChargeRef              : 12,
        shippingChargeRef             : 13,
        discountPercentageRef         : 14,
        discountAmountRef             : 15,
        paymentTypeRef                : 16,
        paymentModeRef                : 17,
        saveBtnRef                    : 18,
        productNameRef                : 19,
        skuRef                        : 20,
        barcodeRef                    : 21,
        mrpRef                        : 22,
        offerPriceRef                 : 23,
        qtyRef                        : 24,
        cgstRef                       : 25,
        sgstRef                       : 26,
        igstRef                       : 27,
        cessRef                       : 28,
        amountRef                     : 29,
        deleteBtnRef                  : 30,
        addRowRef                     : 31,
        firstIndexProductNameRef      : 190,
        customerListFirstIndexRef     : 1000,
        paymentTypeFirstIndexRef      : 600,
        paymentModeFirstIndexRef      : 700,
        prefixesFirstIndexRef         : 400,
        subPrefixesFirstIndexRef      : 500,
        placeofSupplyFirstIndexRef    : 1100,
    }
}
