export default class GstObject {
  getDefaultValues() {
    return {
      invoiceValue: 0,
      zerotaxable: 0,
      zerosgst: 0,
      zerocgst: 0,
      zeroigst: 0,
      threetaxable: 0,
      threesgst: 0,
      threecgst: 0,
      threeigst: 0,
      fivetaxable: 0,
      fivesgst: 0,
      fivecgst: 0,
      fiveigst: 0,
      twelvetaxable: 0,
      twelvesgst: 0,
      twelvecgst: 0,
      twelveigst: 0,
      eighteentaxable: 0,
      eighteensgst: 0,
      eighteencgst: 0,
      eighteenigst: 0,
      twentyeighttaxable: 0,
      twentyeightsgst: 0,
      twentyeightcgst: 0,
      twentyeightigst: 0,
      roundoff: 0,
      cash: 0,
      creditnote: 0,
      upi: 0,
      card: 0,
      neft: 0,
      cheque: 0,
      giftcard: 0,
      customfinance: 0,
      exchange: 0,
      balancedue: 0,
      itemdisc: 0,
      billdisc: 0
    };
  }
}